[package]
name = "scythe"
version = "0.1.0"
authors = ["dabron"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"